name: Events Demo 1
on:
  pull_request:
    types: 
      - opened
  workflow_dispatch: # manual trigger from Actions tab    
  push:
    branches:
      - main
      - 'dev-*' # matches dev-1, dev-2, dev-feature, etc.
      - 'feat/**' # matches feat/one, feat/two, feat/any/sub/branch, etc.
    paths-ignore: 
      - '.github/workflows/**' # if i changes in the workflow file, don't trigger the workflow 
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."